allow_cache: true
batch_size: 16
config: ./examples/fastspeech/conf/fastspeech.v3.yaml
dev_dir: ./dump/valid
eval_interval_steps: 500
fastspeech_params:
  attention_probs_dropout_prob: 0.1
  duration_predictor_dropout_probs: 0.2
  duration_predictor_filters: 256
  duration_predictor_kernel_sizes: 3
  hidden_act: mish
  hidden_dropout_prob: 0.2
  hidden_size: 384
  initializer_range: 0.02
  intermediate_kernel_size: 3
  intermediate_size: 1024
  max_position_embeddings: 2048
  n_speakers: 1
  num_attention_heads: 2
  num_duration_conv_layers: 2
  num_hidden_layers: 4
  num_mels: 80
  output_attentions: false
  output_hidden_states: false
format: npy
hop_size: 256
is_shuffle: true
log_interval_steps: 200
mel_length_threshold: 32
mixed_precision: false
num_save_intermediate_results: 1
optimizer_params:
  decay_steps: 150000
  end_learning_rate: 5.0e-05
  initial_learning_rate: 0.001
  warmup_proportion: 0.02
  weight_decay: 0.001
outdir: ./examples/fastspeech/exp/train.fastspeech.v3/
remove_short_samples: true
resume: ''
save_interval_steps: 5000
train_dir: ./dump/train
train_max_steps: 200000
use_norm: true
verbose: 1
version: 0.6.1
